# Generated by Django 4.2.7 on 2024-02-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_table_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='upload',
            field=models.ImageField(default=0, upload_to='uploads/% Y/% m/% d/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
